version: '3.8'

services:
  python-app:
    image: python:3.11-slim
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && python app.py"
    ports:
      - "127.0.0.1:8000:5000"
    restart: always
